name             'group'
maintainer       'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license          'Apache v2.0'
description      'Use data_bags to create groups.'
long_description 'Use data_bags to create groups.'
version          '0.1.0'
